package com.bsoft.root.entity;

import java.util.ArrayList;
import java.util.List;

public class PoDeptExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table po_dept
     *
     * @mbg.generated Mon Jun 25 08:17:50 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table po_dept
     *
     * @mbg.generated Mon Jun 25 08:17:50 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table po_dept
     *
     * @mbg.generated Mon Jun 25 08:17:50 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_dept
     *
     * @mbg.generated Mon Jun 25 08:17:50 CST 2018
     */
    public PoDeptExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_dept
     *
     * @mbg.generated Mon Jun 25 08:17:50 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_dept
     *
     * @mbg.generated Mon Jun 25 08:17:50 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_dept
     *
     * @mbg.generated Mon Jun 25 08:17:50 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_dept
     *
     * @mbg.generated Mon Jun 25 08:17:50 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_dept
     *
     * @mbg.generated Mon Jun 25 08:17:50 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_dept
     *
     * @mbg.generated Mon Jun 25 08:17:50 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_dept
     *
     * @mbg.generated Mon Jun 25 08:17:50 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_dept
     *
     * @mbg.generated Mon Jun 25 08:17:50 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_dept
     *
     * @mbg.generated Mon Jun 25 08:17:50 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_dept
     *
     * @mbg.generated Mon Jun 25 08:17:50 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table po_dept
     *
     * @mbg.generated Mon Jun 25 08:17:50 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUpperIdIsNull() {
            addCriterion("UPPER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpperIdIsNotNull() {
            addCriterion("UPPER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpperIdEqualTo(Integer value) {
            addCriterion("UPPER_ID =", value, "upperId");
            return (Criteria) this;
        }

        public Criteria andUpperIdNotEqualTo(Integer value) {
            addCriterion("UPPER_ID <>", value, "upperId");
            return (Criteria) this;
        }

        public Criteria andUpperIdGreaterThan(Integer value) {
            addCriterion("UPPER_ID >", value, "upperId");
            return (Criteria) this;
        }

        public Criteria andUpperIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("UPPER_ID >=", value, "upperId");
            return (Criteria) this;
        }

        public Criteria andUpperIdLessThan(Integer value) {
            addCriterion("UPPER_ID <", value, "upperId");
            return (Criteria) this;
        }

        public Criteria andUpperIdLessThanOrEqualTo(Integer value) {
            addCriterion("UPPER_ID <=", value, "upperId");
            return (Criteria) this;
        }

        public Criteria andUpperIdIn(List<Integer> values) {
            addCriterion("UPPER_ID in", values, "upperId");
            return (Criteria) this;
        }

        public Criteria andUpperIdNotIn(List<Integer> values) {
            addCriterion("UPPER_ID not in", values, "upperId");
            return (Criteria) this;
        }

        public Criteria andUpperIdBetween(Integer value1, Integer value2) {
            addCriterion("UPPER_ID between", value1, value2, "upperId");
            return (Criteria) this;
        }

        public Criteria andUpperIdNotBetween(Integer value1, Integer value2) {
            addCriterion("UPPER_ID not between", value1, value2, "upperId");
            return (Criteria) this;
        }

        public Criteria andDeptNameIsNull() {
            addCriterion("DEPT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andDeptNameIsNotNull() {
            addCriterion("DEPT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andDeptNameEqualTo(String value) {
            addCriterion("DEPT_NAME =", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameNotEqualTo(String value) {
            addCriterion("DEPT_NAME <>", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameGreaterThan(String value) {
            addCriterion("DEPT_NAME >", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameGreaterThanOrEqualTo(String value) {
            addCriterion("DEPT_NAME >=", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameLessThan(String value) {
            addCriterion("DEPT_NAME <", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameLessThanOrEqualTo(String value) {
            addCriterion("DEPT_NAME <=", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameLike(String value) {
            addCriterion("DEPT_NAME like", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameNotLike(String value) {
            addCriterion("DEPT_NAME not like", value, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameIn(List<String> values) {
            addCriterion("DEPT_NAME in", values, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameNotIn(List<String> values) {
            addCriterion("DEPT_NAME not in", values, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameBetween(String value1, String value2) {
            addCriterion("DEPT_NAME between", value1, value2, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptNameNotBetween(String value1, String value2) {
            addCriterion("DEPT_NAME not between", value1, value2, "deptName");
            return (Criteria) this;
        }

        public Criteria andDeptAddressIsNull() {
            addCriterion("DEPT_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andDeptAddressIsNotNull() {
            addCriterion("DEPT_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andDeptAddressEqualTo(String value) {
            addCriterion("DEPT_ADDRESS =", value, "deptAddress");
            return (Criteria) this;
        }

        public Criteria andDeptAddressNotEqualTo(String value) {
            addCriterion("DEPT_ADDRESS <>", value, "deptAddress");
            return (Criteria) this;
        }

        public Criteria andDeptAddressGreaterThan(String value) {
            addCriterion("DEPT_ADDRESS >", value, "deptAddress");
            return (Criteria) this;
        }

        public Criteria andDeptAddressGreaterThanOrEqualTo(String value) {
            addCriterion("DEPT_ADDRESS >=", value, "deptAddress");
            return (Criteria) this;
        }

        public Criteria andDeptAddressLessThan(String value) {
            addCriterion("DEPT_ADDRESS <", value, "deptAddress");
            return (Criteria) this;
        }

        public Criteria andDeptAddressLessThanOrEqualTo(String value) {
            addCriterion("DEPT_ADDRESS <=", value, "deptAddress");
            return (Criteria) this;
        }

        public Criteria andDeptAddressLike(String value) {
            addCriterion("DEPT_ADDRESS like", value, "deptAddress");
            return (Criteria) this;
        }

        public Criteria andDeptAddressNotLike(String value) {
            addCriterion("DEPT_ADDRESS not like", value, "deptAddress");
            return (Criteria) this;
        }

        public Criteria andDeptAddressIn(List<String> values) {
            addCriterion("DEPT_ADDRESS in", values, "deptAddress");
            return (Criteria) this;
        }

        public Criteria andDeptAddressNotIn(List<String> values) {
            addCriterion("DEPT_ADDRESS not in", values, "deptAddress");
            return (Criteria) this;
        }

        public Criteria andDeptAddressBetween(String value1, String value2) {
            addCriterion("DEPT_ADDRESS between", value1, value2, "deptAddress");
            return (Criteria) this;
        }

        public Criteria andDeptAddressNotBetween(String value1, String value2) {
            addCriterion("DEPT_ADDRESS not between", value1, value2, "deptAddress");
            return (Criteria) this;
        }

        public Criteria andDeptLinkmanIsNull() {
            addCriterion("DEPT_LINKMAN is null");
            return (Criteria) this;
        }

        public Criteria andDeptLinkmanIsNotNull() {
            addCriterion("DEPT_LINKMAN is not null");
            return (Criteria) this;
        }

        public Criteria andDeptLinkmanEqualTo(String value) {
            addCriterion("DEPT_LINKMAN =", value, "deptLinkman");
            return (Criteria) this;
        }

        public Criteria andDeptLinkmanNotEqualTo(String value) {
            addCriterion("DEPT_LINKMAN <>", value, "deptLinkman");
            return (Criteria) this;
        }

        public Criteria andDeptLinkmanGreaterThan(String value) {
            addCriterion("DEPT_LINKMAN >", value, "deptLinkman");
            return (Criteria) this;
        }

        public Criteria andDeptLinkmanGreaterThanOrEqualTo(String value) {
            addCriterion("DEPT_LINKMAN >=", value, "deptLinkman");
            return (Criteria) this;
        }

        public Criteria andDeptLinkmanLessThan(String value) {
            addCriterion("DEPT_LINKMAN <", value, "deptLinkman");
            return (Criteria) this;
        }

        public Criteria andDeptLinkmanLessThanOrEqualTo(String value) {
            addCriterion("DEPT_LINKMAN <=", value, "deptLinkman");
            return (Criteria) this;
        }

        public Criteria andDeptLinkmanLike(String value) {
            addCriterion("DEPT_LINKMAN like", value, "deptLinkman");
            return (Criteria) this;
        }

        public Criteria andDeptLinkmanNotLike(String value) {
            addCriterion("DEPT_LINKMAN not like", value, "deptLinkman");
            return (Criteria) this;
        }

        public Criteria andDeptLinkmanIn(List<String> values) {
            addCriterion("DEPT_LINKMAN in", values, "deptLinkman");
            return (Criteria) this;
        }

        public Criteria andDeptLinkmanNotIn(List<String> values) {
            addCriterion("DEPT_LINKMAN not in", values, "deptLinkman");
            return (Criteria) this;
        }

        public Criteria andDeptLinkmanBetween(String value1, String value2) {
            addCriterion("DEPT_LINKMAN between", value1, value2, "deptLinkman");
            return (Criteria) this;
        }

        public Criteria andDeptLinkmanNotBetween(String value1, String value2) {
            addCriterion("DEPT_LINKMAN not between", value1, value2, "deptLinkman");
            return (Criteria) this;
        }

        public Criteria andDeptCreateTimeIsNull() {
            addCriterion("DEPT_CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andDeptCreateTimeIsNotNull() {
            addCriterion("DEPT_CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andDeptCreateTimeEqualTo(String value) {
            addCriterion("DEPT_CREATE_TIME =", value, "deptCreateTime");
            return (Criteria) this;
        }

        public Criteria andDeptCreateTimeNotEqualTo(String value) {
            addCriterion("DEPT_CREATE_TIME <>", value, "deptCreateTime");
            return (Criteria) this;
        }

        public Criteria andDeptCreateTimeGreaterThan(String value) {
            addCriterion("DEPT_CREATE_TIME >", value, "deptCreateTime");
            return (Criteria) this;
        }

        public Criteria andDeptCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("DEPT_CREATE_TIME >=", value, "deptCreateTime");
            return (Criteria) this;
        }

        public Criteria andDeptCreateTimeLessThan(String value) {
            addCriterion("DEPT_CREATE_TIME <", value, "deptCreateTime");
            return (Criteria) this;
        }

        public Criteria andDeptCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("DEPT_CREATE_TIME <=", value, "deptCreateTime");
            return (Criteria) this;
        }

        public Criteria andDeptCreateTimeLike(String value) {
            addCriterion("DEPT_CREATE_TIME like", value, "deptCreateTime");
            return (Criteria) this;
        }

        public Criteria andDeptCreateTimeNotLike(String value) {
            addCriterion("DEPT_CREATE_TIME not like", value, "deptCreateTime");
            return (Criteria) this;
        }

        public Criteria andDeptCreateTimeIn(List<String> values) {
            addCriterion("DEPT_CREATE_TIME in", values, "deptCreateTime");
            return (Criteria) this;
        }

        public Criteria andDeptCreateTimeNotIn(List<String> values) {
            addCriterion("DEPT_CREATE_TIME not in", values, "deptCreateTime");
            return (Criteria) this;
        }

        public Criteria andDeptCreateTimeBetween(String value1, String value2) {
            addCriterion("DEPT_CREATE_TIME between", value1, value2, "deptCreateTime");
            return (Criteria) this;
        }

        public Criteria andDeptCreateTimeNotBetween(String value1, String value2) {
            addCriterion("DEPT_CREATE_TIME not between", value1, value2, "deptCreateTime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table po_dept
     *
     * @mbg.generated do_not_delete_during_merge Mon Jun 25 08:17:50 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table po_dept
     *
     * @mbg.generated Mon Jun 25 08:17:50 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}