package com.bsoft.root.entity;

public class PoRoleAuthority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column po_role_authority.ID
     *
     * @mbg.generated Sun Jul 01 17:57:02 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column po_role_authority.ROLE_ID
     *
     * @mbg.generated Sun Jul 01 17:57:02 CST 2018
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column po_role_authority.AUTHORITY_ID
     *
     * @mbg.generated Sun Jul 01 17:57:02 CST 2018
     */
    private Integer authorityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column po_role_authority.ID
     *
     * @return the value of po_role_authority.ID
     *
     * @mbg.generated Sun Jul 01 17:57:02 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column po_role_authority.ID
     *
     * @param id the value for po_role_authority.ID
     *
     * @mbg.generated Sun Jul 01 17:57:02 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column po_role_authority.ROLE_ID
     *
     * @return the value of po_role_authority.ROLE_ID
     *
     * @mbg.generated Sun Jul 01 17:57:02 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column po_role_authority.ROLE_ID
     *
     * @param roleId the value for po_role_authority.ROLE_ID
     *
     * @mbg.generated Sun Jul 01 17:57:02 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column po_role_authority.AUTHORITY_ID
     *
     * @return the value of po_role_authority.AUTHORITY_ID
     *
     * @mbg.generated Sun Jul 01 17:57:02 CST 2018
     */
    public Integer getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column po_role_authority.AUTHORITY_ID
     *
     * @param authorityId the value for po_role_authority.AUTHORITY_ID
     *
     * @mbg.generated Sun Jul 01 17:57:02 CST 2018
     */
    public void setAuthorityId(Integer authorityId) {
        this.authorityId = authorityId;
    }
}