package com.bsoft.root.mappers;

import com.bsoft.root.entity.PoDept;
import com.bsoft.root.entity.PoDeptExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PoDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_dept
     *
     * @mbg.generated Mon Jun 25 08:17:50 CST 2018
     */
    long countByExample(PoDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_dept
     *
     * @mbg.generated Mon Jun 25 08:17:50 CST 2018
     */
    int deleteByExample(PoDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_dept
     *
     * @mbg.generated Mon Jun 25 08:17:50 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_dept
     *
     * @mbg.generated Mon Jun 25 08:17:50 CST 2018
     */
    int insert(PoDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_dept
     *
     * @mbg.generated Mon Jun 25 08:17:50 CST 2018
     */
    int insertSelective(PoDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_dept
     *
     * @mbg.generated Mon Jun 25 08:17:50 CST 2018
     */
    List<PoDept> selectByExample(PoDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_dept
     *
     * @mbg.generated Mon Jun 25 08:17:50 CST 2018
     */
    PoDept selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_dept
     *
     * @mbg.generated Mon Jun 25 08:17:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") PoDept record, @Param("example") PoDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_dept
     *
     * @mbg.generated Mon Jun 25 08:17:50 CST 2018
     */
    int updateByExample(@Param("record") PoDept record, @Param("example") PoDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_dept
     *
     * @mbg.generated Mon Jun 25 08:17:50 CST 2018
     */
    int updateByPrimaryKeySelective(PoDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_dept
     *
     * @mbg.generated Mon Jun 25 08:17:50 CST 2018
     */
    int updateByPrimaryKey(PoDept record);
}