package com.bsoft.root.mappers;

import com.bsoft.root.entity.PoRoleAuthority;
import com.bsoft.root.entity.PoRoleAuthorityExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PoRoleAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_role_authority
     *
     * @mbg.generated Sun Jul 01 17:57:02 CST 2018
     */
    long countByExample(PoRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_role_authority
     *
     * @mbg.generated Sun Jul 01 17:57:02 CST 2018
     */
    int deleteByExample(PoRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_role_authority
     *
     * @mbg.generated Sun Jul 01 17:57:02 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_role_authority
     *
     * @mbg.generated Sun Jul 01 17:57:02 CST 2018
     */
    int insert(PoRoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_role_authority
     *
     * @mbg.generated Sun Jul 01 17:57:02 CST 2018
     */
    int insertSelective(PoRoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_role_authority
     *
     * @mbg.generated Sun Jul 01 17:57:02 CST 2018
     */
    List<PoRoleAuthority> selectByExample(PoRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_role_authority
     *
     * @mbg.generated Sun Jul 01 17:57:02 CST 2018
     */
    PoRoleAuthority selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_role_authority
     *
     * @mbg.generated Sun Jul 01 17:57:02 CST 2018
     */
    int updateByExampleSelective(@Param("record") PoRoleAuthority record, @Param("example") PoRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_role_authority
     *
     * @mbg.generated Sun Jul 01 17:57:02 CST 2018
     */
    int updateByExample(@Param("record") PoRoleAuthority record, @Param("example") PoRoleAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_role_authority
     *
     * @mbg.generated Sun Jul 01 17:57:02 CST 2018
     */
    int updateByPrimaryKeySelective(PoRoleAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_role_authority
     *
     * @mbg.generated Sun Jul 01 17:57:02 CST 2018
     */
    int updateByPrimaryKey(PoRoleAuthority record);

    int batchUpdate(@Param("mainId") Integer mainId, @Param("ids") List<Integer> ids);
}