package com.bsoft.root.mappers;

import com.bsoft.root.entity.PoRole;
import com.bsoft.root.entity.PoRoleExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PoRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_role
     *
     * @mbg.generated Thu Jun 21 16:25:47 CST 2018
     */
    long countByExample(PoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_role
     *
     * @mbg.generated Thu Jun 21 16:25:47 CST 2018
     */
    int deleteByExample(PoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_role
     *
     * @mbg.generated Thu Jun 21 16:25:47 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_role
     *
     * @mbg.generated Thu Jun 21 16:25:47 CST 2018
     */
    int insert(PoRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_role
     *
     * @mbg.generated Thu Jun 21 16:25:47 CST 2018
     */
    int insertSelective(PoRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_role
     *
     * @mbg.generated Thu Jun 21 16:25:47 CST 2018
     */
    List<PoRole> selectByExample(PoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_role
     *
     * @mbg.generated Thu Jun 21 16:25:47 CST 2018
     */
    PoRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_role
     *
     * @mbg.generated Thu Jun 21 16:25:47 CST 2018
     */
    int updateByExampleSelective(@Param("record") PoRole record, @Param("example") PoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_role
     *
     * @mbg.generated Thu Jun 21 16:25:47 CST 2018
     */
    int updateByExample(@Param("record") PoRole record, @Param("example") PoRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_role
     *
     * @mbg.generated Thu Jun 21 16:25:47 CST 2018
     */
    int updateByPrimaryKeySelective(PoRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table po_role
     *
     * @mbg.generated Thu Jun 21 16:25:47 CST 2018
     */
    int updateByPrimaryKey(PoRole record);
}